"""
Stage 8 (validation) — verify ISCE2 geometry products exist and match the
multilooked interferogram dimensions.

stackSentinel's run_12_merge_reference_secondary_slc step multilooks the
per-burst geometry files (topo step output) to merged/geom_reference/,
matching merged/interferograms/*/filt_fine.unw's range/azimuth looks. A
water mask is not produced by this ISCE2 version's topsStack (no DEM-based
water body source configured) -- reported as unavailable rather than
treated as a failure, per the task spec's "if available" wording.

Usage:
    python check_geometry.py --work-dir <isce2 workDir>
"""

import argparse
import sys
from pathlib import Path

import isce  # noqa: F401
import isceobj

REQUIRED = ["hgt.rdr", "lat.rdr", "lon.rdr", "los.rdr", "shadowMask.rdr"]
OPTIONAL = ["waterMask.rdr"]


def image_dims(xml_path: Path):
    img = isceobj.createImage()
    img.load(str(xml_path))
    return img.getLength(), img.getWidth()


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--work-dir", required=True, help="ISCE2 stack workDir")
    args = ap.parse_args()

    work_dir = Path(args.work_dir)
    geom_dir = work_dir / "merged" / "geom_reference"
    ifg_dir = work_dir / "merged" / "interferograms"

    if not geom_dir.is_dir():
        sys.exit(f"No merged/geom_reference/ under {work_dir} -- has run_12 finished yet?")
    if not ifg_dir.is_dir():
        sys.exit(f"No merged/interferograms/ under {work_dir} -- has run_14 finished yet?")

    first_pair = next((d for d in sorted(ifg_dir.iterdir()) if d.is_dir()), None)
    if first_pair is None:
        sys.exit(f"No interferogram pairs found under {ifg_dir}")
    ifg_unw = first_pair / "filt_fine.unw"
    ifg_xml = ifg_unw.with_suffix(ifg_unw.suffix + ".xml")
    if not ifg_xml.exists():
        sys.exit(f"{ifg_xml} missing -- has run_16_unwrap finished yet?")
    ifg_dims = image_dims(ifg_xml)

    missing, mismatched = [], []
    for name in REQUIRED:
        path = geom_dir / name
        xml = path.with_suffix(path.suffix + ".xml")
        if not xml.exists():
            missing.append(name)
            continue
        dims = image_dims(xml)
        if dims != ifg_dims:
            mismatched.append(f"{name}: {dims} != interferogram {ifg_dims} (ref pair {first_pair.name})")

    available_optional = []
    for name in OPTIONAL:
        path = geom_dir / name
        if (path.with_suffix(path.suffix + ".xml")).exists():
            available_optional.append(name)

    if missing:
        print(f"FAIL: missing required geometry product(s): {missing}", file=sys.stderr)
    if mismatched:
        print("FAIL: dimension mismatch:", file=sys.stderr)
        for m in mismatched:
            print(f"  - {m}", file=sys.stderr)
    if missing or mismatched:
        sys.exit(1)

    print(
        f"OK: all {len(REQUIRED)} required geometry products present and match "
        f"interferogram dims {ifg_dims}. "
        f"Optional (shadow/layover, water mask): present={available_optional or 'none'} "
        f"(water mask not generated by this stack -- no water-body DEM source configured)."
    )


if __name__ == "__main__":
    main()
